apiVersion: v1
kind: Service

metadata:
  name: backend-service # DNS name for service discovery
  namespace: h-game
  labels:
    app: backend

spec:
  type: ClusterIP # Internal only (no external access)

  selector:
    app: backend # Route to Pods with this label

  ports:
    - name: http
      protocol: TCP
      port: 3001 # Service port
      targetPort: 3001 # Pod port