apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: h-game
  labels:
    app: postgres

type: Opaque # Generic key-value Secret

data:
  # Base64-encoded values (echo -n 'value' | base64)
  # Decode: echo 'encoded' | base64 -d

  postgres-user: Z2FtZXVzZXI= # gameuser
  postgres-password: ZGV2b3BzMTIz # devops123
  postgres-db: aHVtb3JfbWVtb3J5X2dhbWU= # humor_memory_game